### ISSUE TITLE
Unit testing does not seem to work on node < 10 on build server

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/testing#1]
See https://travis-ci.org/ioBroker/ioBroker.hm-rega/builds/490053666?utm_source=github_status&utm_medium=notification

more specific: https://travis-ci.org/ioBroker/ioBroker.hm-rega/jobs/490053668#L585

**Comment by AlCalzone** [comment]
Are you sure?
https://travis-ci.org/AlCalzone/ioBroker.ble

The problem seems to be more specific than Node <10

**Comment by AlCalzone** [comment]
The problem lies within the `performance-now` module:
```js
// Generated by CoffeeScript 1.12.2
(function() {
  var getNanoSeconds, hrtime, loadTime, moduleLoadTime, nodeLoadTime, upTime;

  if ((typeof performance !== "undefined" && performance !== null) && performance.now) {
    module.exports = function() {
      return performance.now();
    };
  } else if ((typeof process !== "undefined" && process !== null) && process.hrtime) {
    module.exports = function() {
      return (getNanoSeconds() - nodeLoadTime) / 1e6;
    };
    hrtime = process.hrtime;
    getNanoSeconds = function() {
      var hr;
      hr = hrtime();
      return hr[0] * 1e9 + hr[1];
    };
    moduleLoadTime = getNanoSeconds();
    upTime = process.uptime() * 1e9;
    nodeLoadTime = moduleLoadTime - upTime;
  } else if (Date.now) {
    module.exports = function() {
      return Date.now() - loadTime;
    };
    loadTime = Date.now();
  } else {
    module.exports = function() {
      return new Date().getTime() - loadTime;
    };
    loadTime = new Date().getTime();
  }

}).call(this);

//# sourceMappingURL=performance-now.js.map
```

Unfortunately, the given line numbers are wrong, because the unit test loader prepends several lines to the script. I'll have to rewrite that to know where exactly things are failing.

**Comment by foxriver76** [comment]
No, I am not sure, but it is my only reference point. Thanks for investigating.

**Comment by AlCalzone** [comment]
Apparently this has to do with Proxy and native methods. I'm investigating

**Comment by AlCalzone** [comment]
Leaving this here, so I can find it later:
https://github.com/nodejs/node/pull/18131/files#diff-cc63475f116262e9cbea02374e344c01R671

**Comment by AlCalzone** [comment]
Please test with v1.0.4

**Comment by foxriver76** [comment]
works, thank you
