### ISSUE TITLE
adapter.getMessage missing in unit testing

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/testing#11]
see 
https://travis-ci.org/iobroker-community-adapters/ioBroker.email/jobs/504448194#L667
https://travis-ci.org/ioBroker/ioBroker.pushover/jobs/504452430

**Comment by foxriver76** [comment]
it is on the agenda to completly remove this method from the controller. Thus, I would recommend to close this issue.

**Comment by Apollon77** [comment]
see it the same, als remove lenMessage if it is in
