### ISSUE TITLE
"request" module schoul always be available (as in nodejs normally)

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/testing#12]
see https://travis-ci.com/Apollon77/ioBroker.pollenflug/jobs/183691021#L124

**Comment by AlCalzone** [comment]
Request is not always available. If it is needed in a unit test, it needs a mock.

**Comment by Apollon77** [comment]
But it is always available in nodejs since nodejs 6 I think ...

**Comment by Apollon77** [comment]
Formally it needs a mock, but you also could allow the real request to be made

**Comment by AlCalzone** [comment]
> But it is always available in nodejs since nodejs 6 I think ...

Nope:
![grafik](https://user-images.githubusercontent.com/17641229/54110696-605eb480-43e2-11e9-90d9-05a2ecfed177.png)

> but you also could allow the real request to be made

That contradicts the thought behind unit tests. In an integration test, it makes sense.

**Comment by Apollon77** [comment]
I know :-) Thats why ... let me just disable unit testing in that project and done and we need to really good document this unit testing stuff and requirements

**Comment by AlCalzone** [comment]
The mock would only have to return the most basic valid response the user code expects. So there's no way to predefine a mock for it. Something along the lines of:
```js
const requestMock = stub().returns({ /* whatever object you expect that does not cause the adapter to fail */ });
```
or
```js
const requestMock = stub().resolves({ /* whatever object you expect that does not cause the adapter to fail */ });
```
if you are using a promise-based request API.

**Comment by Apollon77** [comment]
You add this to the documentation? Maybe kind of "mocking FAQ?"

**Comment by paveltsytovich** [comment]
> You add this to the documentation? Maybe kind of "mocking FAQ?"

Or small sample for use mocking with this test library

**Comment by AlCalzone** [comment]
Closing in favor of #24 as this is not a bug
