### ISSUE TITLE
Timing issue? Mock unavailable too early?

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/testing#13]
see https://travis-ci.org/ioBroker/ioBroker.admin/jobs/504430088#L1021 ... seems to happen on termination of the adapter

**Comment by AlCalzone** [comment]
> The command "npm run test:unit" exited with 0.

This is the integration test failing, which does not use any mocks.

**Comment by AlCalzone** [comment]
Thats actually a bug in the admin adapter. In `lib/socket.js` the adapter instance stored in the variable `adapter`. Only 4 locations use `that.adapter` (which is never assigned to), one of which is throwing the error here.
