### ISSUE TITLE
Examples do not work

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/testing#151]
I tried to use an example from here: https://github.com/ioBroker/testing#example

And it works only after modifications:
```
assertObjectExists(theObject._id);
```
=> 
```
expect(database.hasObject(theObject._id)).to.be.true;
```

Of course at the start I added `const { expect } = require('chai');`

**Comment by AlCalzone** [comment]
Thanks, I'll check it out.

**Comment by AlCalzone** [comment]
@GermanBluefox Do you have a repo where I can reproduce this error without creating a new one?

**Comment by boellner** [comment]
the Example 
how this can be used in a unit test
is using a deprecated function

/** @deprecated Adapter startup unit tests are no longer supported */
    unit: typeof testAdapterWithMocks;

**Comment by AlCalzone** [comment]
Can you be more specific what the problem is? Screenshot or something is fine.
