### ISSUE TITLE
objects mock no longer necessary

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/testing#187]
Due to https://github.com/ioBroker/ioBroker.js-controller/issues/359 we want to prevent devs from using `adapter.objects` and `adapter.states` thus we should remove providing the functionality of mocking `objects` https://github.com/ioBroker/testing/blob/master/src/tests/unit/mocks/mockObjects.ts

Furthermore, the two pre-implemented methods https://github.com/ioBroker/testing/blob/master/src/tests/unit/mocks/mockObjects.ts#L22 are now part of the adapter class itself.

Thus, the two methods should be provided in this module and the objects mock should be removed.

**Comment by AlCalzone** [comment]
Please test `"testing": "ioBroker/testing#master"` in your adapter.

**Comment by foxriver76** [comment]
Confirmed.
