### ISSUE TITLE
Set engineStrict flag in integration tests

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/testing#217]
to catch potential incompatibilities with the new fixer/installer versions

**Comment by Apollon77** [comment]
but only if nodejs >=10 because else all nodejs 8 test break!

**Comment by AlCalzone** [comment]
I thought we were going to downgrade semver?

**Comment by Apollon77** [comment]
Yes but usually tests run against master ... and master will be pre-3.0 and so nodejs 8 killed ... or we disable nodejs 8 testing right with the release of the testing lib ... or make as major and tell devs to do it when updating

**Comment by AlCalzone** [comment]
I don't see the problem?! engineStrict is only incompatible with `semver@>=7` right now. What does this have to to with Node.js 8 otherwise?

**Comment by Apollon77** [comment]
Ok ... now i get it. you do not really install js-controller ... or ?!

**Comment by AlCalzone** [comment]
I do.

**Comment by Apollon77** [comment]
you're right. Thank you!

**Comment by AlCalzone** [comment]
Oh, now I get it. The master branch is already at 3.0.0 and has the incompatible dependency.
