### ISSUE TITLE
 adapter.removeAllListeners is not a function in unit

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/testing#22]
https://travis-ci.org/Apollon77/iobroker.km200/jobs/504455625#L698

**Comment by AlCalzone** [comment]
The method was implemented, but unit tests in km200 are still not working. Normal startup can be fixed by fake-implementing subscribeStates.
```js
tests.unit(path.join(__dirname, '..'), {
	defineMockBehavior(db, adapter) {
		adapter.subscribeStates.callsFake((...args) => {
			const cb = args[args.length-1];
			if (typeof cb === "function") cb();
		})
	}
});
```
Compact mode doesn't work and I don't understand the spaghetti code.
