### ISSUE TITLE
Create mock separately for each adapter`s instance

### ISSUE THREAD

**Issue by paveltsytovich** [ioBroker/testing#25]
Hi,

I use `SerialPort.MockBinding` and inject mock into my adapter. **MockBinding** require call **CreatePort** method with port path, for example _/dev/ttyUSB0_. Test library run few instance of adapter (normal and compact mode). In second instance of adapter I catch error 'can't open port. Port is locked'.  I need create mock separately per each adapter`s instance. Ho can I do it?

**Comment by Apollon77** [comment]
Did you mke sure that in "unload" you cleanly disconnect fro the serial pot? Then the port should get unlocked again. Mke sure to use "on(unload)" to cleanup everything and call the callback when done

**Comment by AlCalzone** [comment]
And make sure to install the latest version of @iobroker/testing - I recently fixed a bug regarding the unload behavior

**Comment by AlCalzone** [comment]
Duplicate of: #15

**Comment by paveltsytovich** [comment]
I update iobroker/testing library, but hasn't effect. In uload handler I put following code:

`     if(this.serialport.isOpen) {
				this.serialport.close();				
	}
	delete this.serialport;
`
But, I receive error again

> 1) Test the adapter (in a mocked environment)
> base.js:266
>        The adapter starts in compact mode:
>      Uncaught Error: Port is locked cannot open

My adapter place here : https://github.com/paveltsytovich/ioBroker.noolitef/blob/feature/Binding/main.js

**Comment by AlCalzone** [comment]
Thanks, I'll try to find out whats going on later.

**Comment by Apollon77** [comment]
maybe close is executed asic and thats why callback too fast?

**Comment by paveltsytovich** [comment]
https://travis-ci.org/paveltsytovich/ioBroker.noolitef/jobs/505633377. Full log with error

**Comment by AlCalzone** [comment]
`SerialPort.open` and `SerialPort.close` both return a `Promise`. Try to `await` the methods to make sure the code doesn't continue while the port is still opening/closing: 
```js
	async onReady() {
		//TO DO
		this.serialport = new SerialPort('/dev/ttyUSB0');//TODO
		if(!this.serialport.isOpen && !this.serialport.opening)
			await this.serialport.open();
		// in this template all states changes inside the adapters namespace are subscribed
		this.subscribeStates('*');
		this.log.debug('adapter ' + this.name + 'is ready');
}
```

and

```js
async onUnload(callback) {
	try {
		if(this.serialport.isOpen) {
			await this.serialport.close();
		}
		delete this.serialport;
		this.log.info('cleaned everything up...');
		callback();
	} catch (e) {
		callback();
	}
}
```

**Comment by AlCalzone** [comment]
@paveltsytovich I have a PR for you that fixes the unit tests. The problem was that you did not wait for the port to be opened, so when unload was called, it wasn't open yet and could not be closed.

**Comment by paveltsytovich** [comment]
Wow! Many thanks. All work fine :)
