### ISSUE TITLE
How I use two tests.unit in one project

### ISSUE THREAD

**Issue by paveltsytovich** [ioBroker/testing#28]
Hi,

I need write unit test for correct sync object iobroker database with my config from index_m.html and correct change state in object tree after my adapter receive data packet from low-level device. I decide write this tests in separately files. I created two files with same code:
```
tests.unit(path.join(__dirname, '..'), {
	allowedExitCodes: [11],
	additionalMockedModules: {
		'serialport': FakeSerialPort
	},
...
```
When I run tests my adapter crashed with exception:
  

>    at Object.<anonymous> (node_modules/@iobroker/testing/build/tests/unit/index.js:91:21)
>       at Generator.next (<anonymous>)
>       at /home/pavel/Development/nordica/iobroker.noolitef/node_modules/@iobroker/testing/build/tests/unit/index.js:9:71
>       at new Promise (<anonymous>)
>       at __awaiter (node_modules/@iobroker/testing/build/tests/unit/index.js:5:12)
>       at Suite.describe (node_modules/@iobroker/testing/build/tests/unit/index.js:53:66)
>       at Object.testAdapterWithMocks [as unit] (node_modules/@iobroker/testing/build/tests/unit/index.js:53:5)
>       at Object.<anonymous> (test/unit-objectsync.js:10:7)
>       at require (internal/module.js:11:18)
>       at Array.forEach (<anonymous>)
>       at startup (bootstrap_node.js:204:16)
>       at bootstrap_node.js:625:3
> 

How I can fix? 

Thanks

**Comment by paveltsytovich** [comment]
Some append. Fail test message:
1) Uncaught error outside test suite:
base.js:266
     Uncaught TypeError: Cannot redefine property: readyHandler

**Comment by AlCalzone** [comment]
You cannot use the predefined unit test twice. Either import your additional tests from other files inside `defineAdditionalTests`, or write your own separate test files that only use the helper methods described here: https://github.com/ioBroker/testing#helper-functions-for-your-own-tests.

The first thing could look like this:
```js
// test/unit.js:
tests.unit(
  /* ... */
  defineAdditionalTests: require("./your-other-tests.js")
);

// your-other-tests.js:
module.exports = () => {
  // describe, it, ...
}
```

**Comment by paveltsytovich** [comment]
Thanks! I understand
