### ISSUE TITLE
mockAdapterCore.controllerDir not working as expected in some situations

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/testing#343]
The member "controllerDir" of the mocked adapterCore points to a wrong directory in my setup.

My setup is as follows:
ioBroker Folder: `D:\ioBroker\KMProduktiv\`
the adapter code is in `D:\ioBroker\KMProduktiv\iobroker.lovelace`
it is linked to node_modules by npm link, i.e. `D:\iobroker\KMProduktiv\node_modules\iobroker.lovelace -> C:\Users\achim\AppData\Roaming\npm\node_modules\iobroker.lovelace -> D:\iobroker\KMProduktiv\ioBroker.lovelace`

When running `npm run test:unit` in `D:\ioBroker\KM\iobroker.lovelace` it is more or less exptected that controllerDir fails to point to the correct controller dir by a look at the [code](https://github.com/ioBroker/testing/blob/master/src/tests/unit/mocks/mockAdapterCore.ts#L25). But for some reason it fails with the same error when running in `D:\ioBroker\KMProduktiv\node_modules\iobroker.lovelace`, in both cases the controllerDir will be `D:\iobroker\KMProduktiv\iobroker.js-controller`

So in the setup using npm link the mocked adapter core points to the wrong js-controller dir. Not sure how to fix that. 

The location of the adapter code is restricted to `D:\ioBroker\KMProduktiv\iobroker.lovelace` for similar reasons, because otherwise the js-controller can not be found (also it can not be in `D:\ioBroker\KMProduktiv\node_modules\iobroker.lovelace` because of the .git folder, which will prevent NPM from working). The original [code](https://github.com/ioBroker/adapter-core/blob/master/src/utils.ts#L10) of finding js-controller looks very different. May it should be more similar in the mockCase?

**Comment by AlCalzone** [comment]
I need to rethink the unit tests. They don't rely on a real js-controller so the directory is not expected to actually exist or even point to a real controller. The constant merely exists so adapters that import tools.js can use that in unit tests - with a mocked tools.js of course.

Mocking and then copying the original behavior in mocks doesn't make sense.

**Comment by Garfonso** [comment]
In this case it tries to load the letsencrypt.js file from js-controler. So that should be mocked, too?

**Comment by AlCalzone** [comment]
Jup, but like I wrote, this is becoming pointless, so probably just comment out the unit test in travis/Github Actions

**Comment by Garfonso** [comment]
I re-read the documentation and tried a bit more. The issue of loading letsencrypt works, if I change the default unit.js to something like this, i.e. add the mock of letsencrypt. Of course that will fail, if the adapter tries to use something from letsencrypt. Hm... But for the default config it works. ;-)
