### ISSUE TITLE
Make testing JSONL compatible

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/testing#459]
Because controller 4 should automatically use jsonl we also need to adjust testing! The testing library should support both file and jsonl! as a micro update (to ideally get automatically merged by default dependabot config)

**Comment by AlCalzone** [comment]
For reference: We should work with the DB classes directly instead of reading/writing JSON objects

https://github.com/ioBroker/ioBroker.sql/blob/45f9da17b27f8929d6fccb1a89b834538c0d14d1/test/lib/setup.js#L727-L827
