### ISSUE TITLE
Workflow fails when installing VIS (dependency)

### ISSUE THREAD

**Issue by gaudes** [ioBroker/testing#467]
Hey,

I'm not sure where to open this issue.

In my project I currently have the problem, that my test-and-release workflow fails after 30 minutes when trying to install VIS, which is a dependency.

This is my project:
https://github.com/gaudes/ioBroker.slideshow

Attached is the log from the workflow.
[2_Run ioBrokertesting-action-adapter@v1.txt](https://github.com/ioBroker/testing/files/7981621/2_Run.ioBrokertesting-action-adapter%40v1.txt)

Kind regards,

Ralf

**Comment by AlCalzone** [comment]
Duplicate of #466

**Comment by AlCalzone** [comment]
But thanks :)

**Comment by AlCalzone** [comment]
Fixed in 2.5.4
