### ISSUE TITLE
Update required attributes for io-package.json

### ISSUE THREAD

**Issue by hacki11** [ioBroker/testing#47]
Please add the following attribute:
"common.news" found in io-package.json
in
https://github.com/ioBroker/testing/blob/396561c0ac1a63718e362c0f77148bb153b57df1/src/tests/packageFiles/index.ts#L96

news is a required attribute which is checked by ioBroker Adapter checker.

**Comment by AlCalzone** [comment]
Thanks!

**Comment by AlCalzone** [comment]
Fixed in 96b9138f7a2a95671e95dd33d29cab0d64937d5f
