### ISSUE TITLE
Allow schedule adapters to quit immediately (don't check for .alive)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/testing#474]
I've received the following issue with integration tests for my schedule adapter:

```
  0 passing (57s)
  1 failing

  1) Test the adapter (in a live environment)
       The adapter starts:
     Error: The adapter startup was interrupted unexpectedly with code 0
      at TestHarness.<anonymous> (node_modules/@iobroker/testing/build/tests/integration/index.js:119:32)
      at ChildProcess.onClose (node_modules/@iobroker/testing/build/tests/integration/lib/harness.js:144:18)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
```

Solution 1:

Add a timeout before the adapter stops (not that nice)

Solution 2:

Add ``allowedExitCodes: [0]`` to integration test configuration.

**It would be great, if the test framework allows schedule adapters to exit (don't check for .alive)**

**Comment by AlCalzone** [comment]
Can you give me a link to the affected adapter? Makes it easier to verify that the test changes work.

**Comment by klein0r** [comment]
Release Script of Birthday adapter failed because of this behaviour. Just checkout tag 1.1.2

https://github.com/klein0r/ioBroker.birthdays/tree/v1.1.2

See https://github.com/klein0r/ioBroker.birthdays/actions/runs/1905833107 for details

**Comment by AlCalzone** [comment]
fixed in 2.5.5

**Comment by klein0r** [comment]
I've never used those adapter types. But is this also related to type "once" or "subscribe"?
I don't even know how these are supposed to work 😄 Just a question

**Comment by AlCalzone** [comment]
@Apollon77 ?

**Comment by Apollon77** [comment]
* once: When you start the adapter then the process is executed, but controller allows it to exit anytime and still consider the adapter as "ok". This is  mostly used by "www only" adapters that maybe want to update stuff on start
* subscribe: When I know correctly the adapter-konfig contains a state where controller subscribes too and when it is changed then the process is started once. No idea if we have such an adapter currently at all

**Comment by Apollon77** [comment]
but to answert question: most likely obnce and subscribe also end themself when they did their work

**Comment by klein0r** [comment]
@AlCalzone The question was related to this code: https://github.com/ioBroker/ioBroker.js-controller/blob/9ce695a3355a5f2e59532c070a55fdb76e0185b3/packages/adapter/src/lib/adapter/adapter.js#L8932-L8943

``subscribe``, ``schedule`` and ``once`` are handled in the same way - so **maybe** testing should allow the stop for all there types, too.

**Comment by klein0r** [comment]
Just tested the new version - works perfectly! Thanks a lot 🚀

**Comment by AlCalzone** [comment]
Ok I'll update the check to include both of these.
