### ISSUE TITLE
Unexpected Token Error for "Test and Release" Action

### ISSUE THREAD

**Issue by SKB-CGN** [ioBroker/testing#525]
Hi,
with the new testing it gives me the following error:

`> iobroker.energiefluss@1.1.1 test:unit /home/runner/work/ioBroker.energiefluss/ioBroker.energiefluss
> mocha test/unit --exit

/home/runner/work/ioBroker.energiefluss/ioBroker.energiefluss/node_modules/@iobroker/testing/build/tests/integration/index.js:65
        const dbConnection = new dbConnection_1.DBConnection(appName, testDir, (0, logger_1.createLogger)(options.loglevel **??** "debug"));
                                                                                                                            ^

SyntaxError: Unexpected token '?'`
![2022-09-01 13_58_53-Merge pull request #21 from SKB-CGN_dependabot_npm_and_yarn_iobroker_… · SKB-CGN](https://user-images.githubusercontent.com/58603329/187908620-8e740da1-2cd1-4460-b0b1-67aa321e404e.png)

**Comment by AlCalzone** [comment]
You merged this PR (which contains a breaking change - major version update!) although testing failed:
https://github.com/SKB-CGN/ioBroker.energiefluss/pull/21

![grafik](https://user-images.githubusercontent.com/17641229/187913826-7eb3b1c7-04da-4fcc-983f-edb5c25fcea6.png)

and without reading the changelog

![grafik](https://user-images.githubusercontent.com/17641229/187913904-1d0577c6-7c2a-4e8b-872e-fb2e20fa409d.png)

Remove Node.js 12 from [your testing](https://github.com/SKB-CGN/ioBroker.energiefluss/blob/main/.github/workflows/test-and-release.yml#L38).
And while you're at it, add 18.x to that line and change https://github.com/SKB-CGN/ioBroker.energiefluss/blob/f9fe18fe44db85ae44a04923d626dce4649d0976/.github/workflows/test-and-release.yml#L26 to `16.x`

**Comment by SKB-CGN** [comment]
Absolutely right. I didn't recognize the scrollbar on the right, which would show the breaking chang3s after scrolling ;)

Thank you very much!
