### ISSUE TITLE
Mock object inject into adapter

### ISSUE THREAD

**Issue by paveltsytovich** [ioBroker/testing#7]
Hi,

I writing adapter for iot-system (noolite-F). I need inject in my adapter mock object of my low-level driver, but I don`t know how I do it. Please see for detail https://github.com/paveltsytovich/ioBroker.noolitef/blob/feature/Binding/main.js. 
All methods in this class will works with my low-level driver. I want use mock object of it driver for test driven development purpose. I develop my adapter with new test classess patterns for iobroker

Thanks for help

**Comment by AlCalzone** [comment]
I don't see where you are using the low-level driver. Please take a look at my BLE adapter that mocks the `noble` library in its unit tests:
https://github.com/AlCalzone/ioBroker.ble/blob/master/test/unit.js

Lines 10-13 define how the mock behaves (in this case, it does nothing but report a state of "poweredOff"). This is where you define the base object with a couple of stubs.

Lines 18-21 declare that the modules "noble" and "@abandonware/noble" should be replaced by the mock object when loaded with `require`.

Inside `defineAdditionalTests` you write your actual tests, e.g.
```js
defineAdditionalTests() {
    describe("...", () => {
        afterEach(() => { /* reset the mock history (and behavior) */ });
        it("does stuff", () => {
            mock.method.returns("something");
            // do something
            // assert something;
        });
    });
}
```

**Comment by paveltsytovich** [comment]
Thanks for your reply. It became more clear how to use mock while development with test iobroker's adapter
