### ISSUE TITLE
In unit test createMocks create wrong adapter

### ISSUE THREAD

**Issue by paveltsytovich** [ioBroker/testing#8]
Hi,

I try use code from README.md  sample in unit test (not integration)

`const { database, adapter } = utils.unit.createMocks();`

In adapter variable I see adapter with "test.0" name, but I expected my adapter  ("noolitef.0") to be created.
It`s bug or feature? What different tests purpose for iobroker development between unit and integration tests?

Thanks

**Comment by AlCalzone** [comment]
> What different tests purpose for iobroker development between unit and integration tests?

Unit tests are meant to test single small units of code, e.g. functions, without depending on external modules and such. Integration tests are much more extensive and usually involve databases and such. For ioBroker this means:
* Unit tests stub out all external dependencies with mocks that behave (almost) like them and can test the adapter startup and other functionality in a matter of milliseconds
* Integration tests install a full-blown js-controller in the latest version and run tests against a real objects and states db.

> In adapter variable I see adapter with "test.0" name, but I expected my adapter ("noolitef.0") to be created. It`s bug or feature?

Does your code to be tested depend on the correct namespace? I thought it was not necessary to set the actual adapter name on the test mock - but it might be. After all, the mock is just an object that behaves a bit like a real adapter, but lets you assert if certain methods were called and how they respond.

**Comment by paveltsytovich** [comment]
Hi,

Thanks you for answer.

My code does not depend on the name of the adapter. I`m understanding of TDD conception :-). 

I understood how to use mock in testing the adapter. Thanks for the sample code. However, I don’t understand how I can test the state change handler (**onStateChange** in the my adapter). I can't call directly it from my test who are in **defineAdditionalTests** , and can't use adapter's function, for example **setState()**, because all function is stubs.

I need the following:

- Testing correct synchronization between admin interface objects (native property in admin javascript page) and objects in iobroker. This operation will place in **onReady** handler

- Testing the correct operation of , **onStateChange** and **onObjectChange**

What do you advise me for solve my tasks?

**Comment by AlCalzone** [comment]
`adapter.setState` and similar methods do exist and work with the underlying mock database. You can assert that the states objects in the database have the correct values/format by using the asserts that are [explained here](https://github.com/ioBroker/testing#helper-functions-for-your-own-tests).

Regarding tests for the ready/statechange/objectchange handlers: This requires a way for you to execute the handlers yourself. The code is already there but I don't think this is currently possible from outside the testing lib. 
I'll try to add a simple way to do that.

**Comment by AlCalzone** [comment]
You can now pass the initializer for the adapter constructor to `createMocks()` in order to overwrite the mock name:
```ts
createMocks({name: "my-adapter"});
```

**Comment by Apollon77** [comment]
Why you did not mde adaptername from io-package as the default name?

**Comment by AlCalzone** [comment]
Because the `createMocks` method is a utility that is independent of io-package.json. It basically accepts any options the adapter constructor accepts too.
I'll think about falling back to reading io-package.json, but that might also be undesired behavior for custom tests.

The predefined tests do use the same name as the adapter because they execute its main file.

**Comment by Apollon77** [comment]
aah yes this sould work too (same name as adapter)
